"""initial schema 16 tables with comments

Revision ID: 2052dfbbf16e
Revises: 
Create Date: 2026-06-17 20:51:37.276404

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2052dfbbf16e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='key 所属用户 sys_user.id'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='用途标签，如 "本地开发" / "oa-定时任务"'),
    sa.Column('key_hash', sa.String(length=64), nullable=False, comment='sk-key 的 sha256 哈希；明文仅创建时返回一次'),
    sa.Column('key_prefix', sa.String(length=16), nullable=False, comment='明文前缀如 "sk-a1b2"，列表脱敏展示（非敏感）'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态 ApiKeyStatus：active | disabled'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间；null=永不过期'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='最后使用时间（异步更新，避免热行）'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 sys_user.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 sys_department.id（逻辑引用），用于数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 sys_user.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.PrimaryKeyConstraint('id'),
    comment='平台 sk-key 凭证：只存哈希（平台仅验签，绝不可逆）'
    )
    op.create_index(op.f('ix_api_key_create_dept'), 'api_key', ['create_dept'], unique=False)
    op.create_index(op.f('ix_api_key_key_hash'), 'api_key', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_key_status'), 'api_key', ['status'], unique=False)
    op.create_index(op.f('ix_api_key_user_id'), 'api_key', ['user_id'], unique=False)
    op.create_index('uq_apikey_hash', 'api_key', ['key_hash'], unique=True)
    op.create_table('channel_key',
    sa.Column('channel_id', sa.BigInteger(), nullable=False, comment='所属渠道 upstream_channel.id'),
    sa.Column('alias', sa.String(length=64), nullable=False, comment='可读标签，如 "anthropic-主号"'),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False, comment='上游厂商 key 密文（Fernet/KMS，绝不存明文）'),
    sa.Column('key_hint', sa.String(length=16), nullable=False, comment='明文末几位如 "...a1b2"，供运维识别'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态 ChannelKeyStatus：active | disabled（cooldown 是 Redis 运行态，不入库）'),
    sa.Column('rpm_limit', sa.Integer(), nullable=True, comment='单 deployment rpm 上限（喂给 litellm.Router）；null=不限'),
    sa.Column('tpm_limit', sa.Integer(), nullable=True, comment='单 deployment tpm 上限；null=不限'),
    sa.Column('weight', sa.Integer(), nullable=False, comment='加权轮询权重'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='渠道内 key 排序（小者先；0=主）'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='最后使用时间（异步更新，用于僵尸 key 发现）'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 sys_user.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 sys_department.id（逻辑引用），用于数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 sys_user.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.PrimaryKeyConstraint('id'),
    comment='号池条目：渠道下的一把上游 key（可逆加密存储）'
    )
    op.create_index(op.f('ix_channel_key_channel_id'), 'channel_key', ['channel_id'], unique=False)
    op.create_index('ix_channel_key_channel_status', 'channel_key', ['channel_id', 'status'], unique=False)
    op.create_index(op.f('ix_channel_key_create_dept'), 'channel_key', ['create_dept'], unique=False)
    op.create_index(op.f('ix_channel_key_status'), 'channel_key', ['status'], unique=False)
    op.create_table('logical_model',
    sa.Column('name', sa.String(length=64), nullable=False, comment='员工作为 model 发送的统一模型名，如 "claude-sonnet"'),
    sa.Column('display_name', sa.String(length=64), nullable=False, comment='前端展示名，如 "Claude Sonnet (推荐)"'),
    sa.Column('category', sa.String(length=32), nullable=True, comment='模型选择器分组，如 "通用"/"代码"/"长文"'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('context_length', sa.Integer(), nullable=True, comment='null=运行时由 litellm.get_max_tokens() 解析；有值=显式覆盖'),
    sa.Column('price_input', sa.Numeric(precision=12, scale=6), nullable=True, comment='输入计价系数（每百万 token，内部成本点非美元）；null=不单独计价'),
    sa.Column('price_output', sa.Numeric(precision=12, scale=6), nullable=True, comment='输出计价系数（每百万 token，内部成本点非美元）；null=不单独计价'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态 ActiveStatus：active | disabled'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 sys_user.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 sys_department.id（逻辑引用），用于数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 sys_user.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.PrimaryKeyConstraint('id'),
    comment='逻辑模型：员工看到的统一模型名'
    )
    op.create_index(op.f('ix_logical_model_category'), 'logical_model', ['category'], unique=False)
    op.create_index(op.f('ix_logical_model_create_dept'), 'logical_model', ['create_dept'], unique=False)
    op.create_index(op.f('ix_logical_model_status'), 'logical_model', ['status'], unique=False)
    op.create_index('uq_logical_model_name_active', 'logical_model', ['name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('model_deployment',
    sa.Column('logical_model_id', sa.BigInteger(), nullable=False, comment='逻辑模型 logical_model.id'),
    sa.Column('channel_id', sa.BigInteger(), nullable=False, comment='渠道 upstream_channel.id'),
    sa.Column('upstream_model', sa.String(length=128), nullable=False, comment='该渠道下的上游真实模型名，如 claude-sonnet-4-6'),
    sa.Column('weight', sa.Integer(), nullable=False, comment='跨渠道权重'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='跨渠道主备（小者先；0=主）'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态 ActiveStatus：active | disabled'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 sys_user.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 sys_department.id（逻辑引用），用于数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 sys_user.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.PrimaryKeyConstraint('id'),
    comment='模型部署：逻辑模型↔渠道 的承载关系（N:M 核心）'
    )
    op.create_index('ix_deployment_logical_status', 'model_deployment', ['logical_model_id', 'status'], unique=False)
    op.create_index(op.f('ix_model_deployment_channel_id'), 'model_deployment', ['channel_id'], unique=False)
    op.create_index(op.f('ix_model_deployment_create_dept'), 'model_deployment', ['create_dept'], unique=False)
    op.create_index(op.f('ix_model_deployment_logical_model_id'), 'model_deployment', ['logical_model_id'], unique=False)
    op.create_index(op.f('ix_model_deployment_status'), 'model_deployment', ['status'], unique=False)
    op.create_index('uq_deployment_logical_model_channel_active', 'model_deployment', ['logical_model_id', 'channel_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('quota',
    sa.Column('scope', sa.String(length=16), nullable=False, comment='配额范围 QuotaScope：user=用户 | department=部门 | global=全局'),
    sa.Column('scope_id', sa.BigInteger(), nullable=True, comment='范围主体 id；scope=global 时为空'),
    sa.Column('logical_model_id', sa.BigInteger(), nullable=True, comment='逻辑模型 logical_model.id；null=该范围跨所有模型的总配额'),
    sa.Column('period', sa.String(length=16), nullable=False, comment='周期 QuotaPeriod：daily=每日 | monthly=每月 | total=永不重置'),
    sa.Column('metric', sa.String(length=16), nullable=False, comment='度量 QuotaMetric：tokens=令牌数 | requests=请求数 | cost=成本点'),
    sa.Column('limit_value', sa.Numeric(precision=14, scale=6), nullable=False, comment='限额上限；精度同 usage_record.cost（tokens/requests 用整数）'),
    sa.Column('enforce', sa.Boolean(), nullable=False, comment='true=超限拒绝(429) | false=仅告警（软配额）'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态 ActiveStatus：active | disabled'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 sys_user.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 sys_department.id（逻辑引用），用于数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 sys_user.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.CheckConstraint("(scope = 'global' AND scope_id IS NULL) OR (scope <> 'global' AND scope_id IS NOT NULL)", name='ck_quota_scope_id_presence'),
    sa.PrimaryKeyConstraint('id'),
    comment='配额配置：运维设的限额规则（非已消耗量，实时用量在 Redis）'
    )
    op.create_index(op.f('ix_quota_create_dept'), 'quota', ['create_dept'], unique=False)
    op.create_index(op.f('ix_quota_logical_model_id'), 'quota', ['logical_model_id'], unique=False)
    op.create_index(op.f('ix_quota_scope'), 'quota', ['scope'], unique=False)
    op.create_index(op.f('ix_quota_scope_id'), 'quota', ['scope_id'], unique=False)
    op.create_index(op.f('ix_quota_status'), 'quota', ['status'], unique=False)
    op.create_index('uq_quota_scope_model_period_metric_active', 'quota', ['scope', 'scope_id', 'logical_model_id', 'period', 'metric'], unique=True, postgresql_nulls_not_distinct=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('sys_department',
    sa.Column('name', sa.String(length=128), nullable=False, comment='部门名称'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父部门 id（指向自身）；顶级为空'),
    sa.Column('external_id', sa.String(length=64), nullable=True, comment='HR/企微 部门 id，用于同步映射'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='同级排序'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 sys_user.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 sys_department.id（逻辑引用），用于数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 sys_user.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统部门：组织部门树（邻接表）'
    )
    op.create_index(op.f('ix_sys_department_create_dept'), 'sys_department', ['create_dept'], unique=False)
    op.create_index(op.f('ix_sys_department_external_id'), 'sys_department', ['external_id'], unique=False)
    op.create_index(op.f('ix_sys_department_parent_id'), 'sys_department', ['parent_id'], unique=False)
    op.create_index('uq_dept_external_active', 'sys_department', ['external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL AND is_deleted = false'))
    op.create_table('sys_menu',
    sa.Column('name', sa.String(length=64), nullable=False, comment='i18n key（如 menu.system.user），前端翻译，非展示文本（G16）'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父节点 id（指向自身）；顶级为空'),
    sa.Column('menu_type', sa.String(length=8), nullable=False, comment='菜单类型 MenuType：catalog=目录 | menu=页面 | button=按钮/权限点'),
    sa.Column('perms', sa.String(length=128), nullable=True, comment='权限码，如 pool:key:add（按钮/API）'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='前端路由（menu 类型）'),
    sa.Column('component', sa.String(length=255), nullable=True, comment='前端组件路径（menu 类型）'),
    sa.Column('query_param', sa.String(length=255), nullable=True, comment='路由查询参数'),
    sa.Column('is_frame', sa.Boolean(), nullable=False, comment='是否外链'),
    sa.Column('is_cache', sa.Boolean(), nullable=False, comment='是否 keep-alive 缓存'),
    sa.Column('icon', sa.String(length=64), nullable=True, comment='图标'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('visible', sa.Boolean(), nullable=False, comment='是否显示；隐藏菜单仍授权，只是不展示'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态 ActiveStatus：active | disabled'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注（name 是不透明 i18n key，此处给开发者读）'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 sys_user.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 sys_department.id（逻辑引用），用于数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 sys_user.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统菜单：统一的菜单/按钮/API 权限节点'
    )
    op.create_index(op.f('ix_sys_menu_create_dept'), 'sys_menu', ['create_dept'], unique=False)
    op.create_index(op.f('ix_sys_menu_parent_id'), 'sys_menu', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_menu_perms'), 'sys_menu', ['perms'], unique=False)
    op.create_table('sys_role',
    sa.Column('name', sa.String(length=64), nullable=False, comment='角色显示名，如 "平台管理员"'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='角色标识，如 "platform_admin"'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态 ActiveStatus：active | disabled'),
    sa.Column('menu_check_strictly', sa.Boolean(), nullable=False, comment='菜单树父子勾选是否严格关联（纯前端 UI 行为）'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 sys_user.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 sys_department.id（逻辑引用）；审计留痕，非数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 sys_user.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统角色：后台 RBAC 角色'
    )
    op.create_index(op.f('ix_sys_role_code'), 'sys_role', ['code'], unique=False)
    op.create_index(op.f('ix_sys_role_create_dept'), 'sys_role', ['create_dept'], unique=False)
    op.create_index('uq_role_code_active', 'sys_role', ['code'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('sys_role_menu',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 sys_role.id'),
    sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='菜单 sys_menu.id'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'menu_id', name='uq_role_menu'),
    comment='角色-菜单权限关联表'
    )
    op.create_index(op.f('ix_sys_role_menu_menu_id'), 'sys_role_menu', ['menu_id'], unique=False)
    op.create_index(op.f('ix_sys_role_menu_role_id'), 'sys_role_menu', ['role_id'], unique=False)
    op.create_table('sys_user',
    sa.Column('employee_no', sa.String(length=64), nullable=False, comment='新工号：HR 权威主键（非空）'),
    sa.Column('legacy_employee_no', sa.String(length=64), nullable=True, comment='旧工号==企微 UserID；仅老员工有'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录名（账密登录用）：非空，业务唯一'),
    sa.Column('real_name', sa.String(length=64), nullable=True, comment='真实姓名'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'),
    sa.Column('mobile', sa.String(length=32), nullable=True, comment='手机号'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='密码哈希（argon2，绝不存明文）；仅管理员有，SSO 用户为空'),
    sa.Column('department_id', sa.BigInteger(), nullable=True, comment='所属部门 sys_department.id（逻辑引用，无物理外键）'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态 UserStatus：active=在职 | disabled=停用/离职'),
    sa.Column('preferred_locale', sa.String(length=16), server_default='zh-CN', nullable=False, comment='语言偏好（G16）：外发消息渲染 + 前端默认 locale 种子'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 sys_user.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 sys_department.id（逻辑引用），用于数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 sys_user.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统用户：员工权威档案，从 HR 同步'
    )
    op.create_index(op.f('ix_sys_user_create_dept'), 'sys_user', ['create_dept'], unique=False)
    op.create_index(op.f('ix_sys_user_department_id'), 'sys_user', ['department_id'], unique=False)
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=False)
    op.create_index(op.f('ix_sys_user_employee_no'), 'sys_user', ['employee_no'], unique=False)
    op.create_index(op.f('ix_sys_user_legacy_employee_no'), 'sys_user', ['legacy_employee_no'], unique=False)
    op.create_index(op.f('ix_sys_user_mobile'), 'sys_user', ['mobile'], unique=False)
    op.create_index(op.f('ix_sys_user_status'), 'sys_user', ['status'], unique=False)
    op.create_index('uq_user_employee_no_active', 'sys_user', ['employee_no'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('uq_user_legacy_no_active', 'sys_user', ['legacy_employee_no'], unique=True, postgresql_where=sa.text('legacy_employee_no IS NOT NULL AND is_deleted = false'))
    op.create_index('uq_user_username_active', 'sys_user', ['username'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('sys_user_oauth',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 sys_user.id（非空，仅硬匹配命中时落库）'),
    sa.Column('source', sa.String(length=32), nullable=False, comment='身份来源 OAuthSource：wecom | ...'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='第三方用户 id（企微 UserID）'),
    sa.Column('nickname', sa.String(length=64), nullable=True, comment='昵称（第三方返回快照，非权威）'),
    sa.Column('avatar', sa.String(length=1000), nullable=True, comment='头像 URL（第三方返回快照）'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱（第三方返回快照）'),
    sa.Column('gender', sa.String(length=16), nullable=True, comment='性别（第三方返回快照）'),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='脱敏白名单档案字段；绝不存 access_token/user_ticket'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 sys_user.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 sys_department.id（逻辑引用），用于数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 sys_user.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户第三方登录身份快照（企微等）'
    )
    op.create_index(op.f('ix_sys_user_oauth_create_dept'), 'sys_user_oauth', ['create_dept'], unique=False)
    op.create_index(op.f('ix_sys_user_oauth_source'), 'sys_user_oauth', ['source'], unique=False)
    op.create_index(op.f('ix_sys_user_oauth_user_id'), 'sys_user_oauth', ['user_id'], unique=False)
    op.create_index(op.f('ix_sys_user_oauth_uuid'), 'sys_user_oauth', ['uuid'], unique=False)
    op.create_index('uq_oauth_source_uuid_active', 'sys_user_oauth', ['source', 'uuid'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('uq_oauth_user_source_active', 'sys_user_oauth', ['user_id', 'source'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 sys_user.id'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 sys_role.id'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role'),
    comment='用户-角色关联表'
    )
    op.create_index(op.f('ix_sys_user_role_role_id'), 'sys_user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_sys_user_role_user_id'), 'sys_user_role', ['user_id'], unique=False)
    op.create_table('upstream_channel',
    sa.Column('name', sa.String(length=64), nullable=False, comment='渠道名，如 anthropic-official / bedrock-claude / deepseek'),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='厂商：anthropic|gemini|deepseek|glm|qwen|mimo...（驱动 litellm 前缀/计价）'),
    sa.Column('protocol', sa.String(length=16), nullable=False, comment='对上游的协议：anthropic|openai|gemini'),
    sa.Column('api_base', sa.String(length=255), nullable=True, comment='上游 base_url；官方厂商为空（litellm 默认）'),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='非密配置（region/api_version）；密钥放 channel_key'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态 ChannelStatus：active | disabled'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 sys_user.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 sys_department.id（逻辑引用），用于数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 sys_user.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.PrimaryKeyConstraint('id'),
    comment='上游渠道：provider + api_base + protocol 接入点'
    )
    op.create_index(op.f('ix_upstream_channel_create_dept'), 'upstream_channel', ['create_dept'], unique=False)
    op.create_index(op.f('ix_upstream_channel_protocol'), 'upstream_channel', ['protocol'], unique=False)
    op.create_index(op.f('ix_upstream_channel_provider'), 'upstream_channel', ['provider'], unique=False)
    op.create_index(op.f('ix_upstream_channel_status'), 'upstream_channel', ['status'], unique=False)
    op.create_index('uq_channel_name_active', 'upstream_channel', ['name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('usage_record',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='计费主体用户 sys_user.id'),
    sa.Column('api_key_id', sa.BigInteger(), nullable=True, comment='发起调用的 api_key.id；直连 SSO 时为空'),
    sa.Column('logical_model_id', sa.BigInteger(), nullable=False, comment='员工请求的逻辑模型 logical_model.id'),
    sa.Column('channel_id', sa.BigInteger(), nullable=True, comment='实际路由到的渠道 upstream_channel.id（事后分析）'),
    sa.Column('upstream_model', sa.String(length=128), nullable=True, comment='实际调用的上游真实模型名'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False, comment='输入 token 数'),
    sa.Column('completion_tokens', sa.Integer(), nullable=False, comment='输出 token 数'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='总 token 数（冗余，便于聚合）'),
    sa.Column('cost', sa.Numeric(precision=14, scale=6), nullable=True, comment='调用时冻结的内部成本：(in*price_in + out*price_out) / 1e6'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='结果 UsageStatus：success | error | timeout'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='端到端延迟（毫秒）'),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='贯穿网关日志/Redis 的关联 id（无 call_audit 表）'),
    sa.Column('downgraded_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='本次调用被丢弃/降级的特性（G13）；null/空=未降级'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.PrimaryKeyConstraint('id'),
    comment='用量流水：每次 LLM 调用一行，记账/报表/降级率统计的权威源'
    )
    op.create_index('ix_usage_logical_model_created', 'usage_record', ['logical_model_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_record_api_key_id'), 'usage_record', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_usage_record_channel_id'), 'usage_record', ['channel_id'], unique=False)
    op.create_index(op.f('ix_usage_record_logical_model_id'), 'usage_record', ['logical_model_id'], unique=False)
    op.create_index(op.f('ix_usage_record_request_id'), 'usage_record', ['request_id'], unique=False)
    op.create_index(op.f('ix_usage_record_status'), 'usage_record', ['status'], unique=False)
    op.create_index(op.f('ix_usage_record_user_id'), 'usage_record', ['user_id'], unique=False)
    op.create_index('ix_usage_user_created', 'usage_record', ['user_id', 'created_at'], unique=False)
    op.create_table('user_model_grant',
    sa.Column('scope', sa.String(length=16), nullable=False, comment='授予范围 GrantScope：user=用户 | department=部门'),
    sa.Column('scope_id', sa.BigInteger(), nullable=False, comment='scope=user 指向 sys_user.id；scope=department 指向 sys_department.id'),
    sa.Column('logical_model_id', sa.BigInteger(), nullable=False, comment='逻辑模型 logical_model.id'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否该 scope 的默认模型（员工未传 model 时用）'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 sys_user.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 sys_department.id（逻辑引用），用于数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 sys_user.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.PrimaryKeyConstraint('id'),
    comment='模型分配：谁（用户/部门）可用哪些逻辑模型 + 默认模型'
    )
    op.create_index(op.f('ix_user_model_grant_create_dept'), 'user_model_grant', ['create_dept'], unique=False)
    op.create_index(op.f('ix_user_model_grant_logical_model_id'), 'user_model_grant', ['logical_model_id'], unique=False)
    op.create_index(op.f('ix_user_model_grant_scope'), 'user_model_grant', ['scope'], unique=False)
    op.create_index(op.f('ix_user_model_grant_scope_id'), 'user_model_grant', ['scope_id'], unique=False)
    op.create_index('uq_grant_one_default', 'user_model_grant', ['scope', 'scope_id'], unique=True, postgresql_where=sa.text('is_default = true AND is_deleted = false'))
    op.create_index('uq_grant_scope_logical_model_active', 'user_model_grant', ['scope', 'scope_id', 'logical_model_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_grant_scope_logical_model_active', table_name='user_model_grant', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('uq_grant_one_default', table_name='user_model_grant', postgresql_where=sa.text('is_default = true AND is_deleted = false'))
    op.drop_index(op.f('ix_user_model_grant_scope_id'), table_name='user_model_grant')
    op.drop_index(op.f('ix_user_model_grant_scope'), table_name='user_model_grant')
    op.drop_index(op.f('ix_user_model_grant_logical_model_id'), table_name='user_model_grant')
    op.drop_index(op.f('ix_user_model_grant_create_dept'), table_name='user_model_grant')
    op.drop_table('user_model_grant')
    op.drop_index('ix_usage_user_created', table_name='usage_record')
    op.drop_index(op.f('ix_usage_record_user_id'), table_name='usage_record')
    op.drop_index(op.f('ix_usage_record_status'), table_name='usage_record')
    op.drop_index(op.f('ix_usage_record_request_id'), table_name='usage_record')
    op.drop_index(op.f('ix_usage_record_logical_model_id'), table_name='usage_record')
    op.drop_index(op.f('ix_usage_record_channel_id'), table_name='usage_record')
    op.drop_index(op.f('ix_usage_record_api_key_id'), table_name='usage_record')
    op.drop_index('ix_usage_logical_model_created', table_name='usage_record')
    op.drop_table('usage_record')
    op.drop_index('uq_channel_name_active', table_name='upstream_channel', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_upstream_channel_status'), table_name='upstream_channel')
    op.drop_index(op.f('ix_upstream_channel_provider'), table_name='upstream_channel')
    op.drop_index(op.f('ix_upstream_channel_protocol'), table_name='upstream_channel')
    op.drop_index(op.f('ix_upstream_channel_create_dept'), table_name='upstream_channel')
    op.drop_table('upstream_channel')
    op.drop_index(op.f('ix_sys_user_role_user_id'), table_name='sys_user_role')
    op.drop_index(op.f('ix_sys_user_role_role_id'), table_name='sys_user_role')
    op.drop_table('sys_user_role')
    op.drop_index('uq_oauth_user_source_active', table_name='sys_user_oauth', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('uq_oauth_source_uuid_active', table_name='sys_user_oauth', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_sys_user_oauth_uuid'), table_name='sys_user_oauth')
    op.drop_index(op.f('ix_sys_user_oauth_user_id'), table_name='sys_user_oauth')
    op.drop_index(op.f('ix_sys_user_oauth_source'), table_name='sys_user_oauth')
    op.drop_index(op.f('ix_sys_user_oauth_create_dept'), table_name='sys_user_oauth')
    op.drop_table('sys_user_oauth')
    op.drop_index('uq_user_username_active', table_name='sys_user', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('uq_user_legacy_no_active', table_name='sys_user', postgresql_where=sa.text('legacy_employee_no IS NOT NULL AND is_deleted = false'))
    op.drop_index('uq_user_employee_no_active', table_name='sys_user', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_sys_user_status'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_mobile'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_legacy_employee_no'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_employee_no'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_department_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_create_dept'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_role_menu_role_id'), table_name='sys_role_menu')
    op.drop_index(op.f('ix_sys_role_menu_menu_id'), table_name='sys_role_menu')
    op.drop_table('sys_role_menu')
    op.drop_index('uq_role_code_active', table_name='sys_role', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_sys_role_create_dept'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_code'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_menu_perms'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_parent_id'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_create_dept'), table_name='sys_menu')
    op.drop_table('sys_menu')
    op.drop_index('uq_dept_external_active', table_name='sys_department', postgresql_where=sa.text('external_id IS NOT NULL AND is_deleted = false'))
    op.drop_index(op.f('ix_sys_department_parent_id'), table_name='sys_department')
    op.drop_index(op.f('ix_sys_department_external_id'), table_name='sys_department')
    op.drop_index(op.f('ix_sys_department_create_dept'), table_name='sys_department')
    op.drop_table('sys_department')
    op.drop_index('uq_quota_scope_model_period_metric_active', table_name='quota', postgresql_nulls_not_distinct=True, postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_quota_status'), table_name='quota')
    op.drop_index(op.f('ix_quota_scope_id'), table_name='quota')
    op.drop_index(op.f('ix_quota_scope'), table_name='quota')
    op.drop_index(op.f('ix_quota_logical_model_id'), table_name='quota')
    op.drop_index(op.f('ix_quota_create_dept'), table_name='quota')
    op.drop_table('quota')
    op.drop_index('uq_deployment_logical_model_channel_active', table_name='model_deployment', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_model_deployment_status'), table_name='model_deployment')
    op.drop_index(op.f('ix_model_deployment_logical_model_id'), table_name='model_deployment')
    op.drop_index(op.f('ix_model_deployment_create_dept'), table_name='model_deployment')
    op.drop_index(op.f('ix_model_deployment_channel_id'), table_name='model_deployment')
    op.drop_index('ix_deployment_logical_status', table_name='model_deployment')
    op.drop_table('model_deployment')
    op.drop_index('uq_logical_model_name_active', table_name='logical_model', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_logical_model_status'), table_name='logical_model')
    op.drop_index(op.f('ix_logical_model_create_dept'), table_name='logical_model')
    op.drop_index(op.f('ix_logical_model_category'), table_name='logical_model')
    op.drop_table('logical_model')
    op.drop_index(op.f('ix_channel_key_status'), table_name='channel_key')
    op.drop_index(op.f('ix_channel_key_create_dept'), table_name='channel_key')
    op.drop_index('ix_channel_key_channel_status', table_name='channel_key')
    op.drop_index(op.f('ix_channel_key_channel_id'), table_name='channel_key')
    op.drop_table('channel_key')
    op.drop_index('uq_apikey_hash', table_name='api_key')
    op.drop_index(op.f('ix_api_key_user_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_status'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_key_hash'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_create_dept'), table_name='api_key')
    op.drop_table('api_key')
    # ### end Alembic commands ###
