"""add sys_config platform config table

Revision ID: 86f8cd47f40f
Revises: dd58396c39de
Create Date: 2026-06-18 02:32:09.084687

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f8cd47f40f'
down_revision: str | None = 'dd58396c39de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_config',
    sa.Column('config_key', sa.String(length=128), nullable=False, comment='配置键（全局唯一），如 auth.login_max_failures'),
    sa.Column('config_value', sa.Text(), nullable=False, comment='配置值，统一以字符串存储；按 value_type 解析'),
    sa.Column('value_type', sa.String(length=16), nullable=False, comment='值类型 ConfigValueType：string | int | bool | json'),
    sa.Column('config_name', sa.String(length=128), nullable=False, comment='人类可读名称（管理后台展示）'),
    sa.Column('is_builtin', sa.Boolean(), nullable=False, comment='是否平台内置项：true=可改不可删'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 sys_user.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 sys_department.id（逻辑引用），用于数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 sys_user.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.PrimaryKeyConstraint('id'),
    comment='平台配置：键值型运行时参数（typed），内置项可改不可删'
    )
    op.create_index(op.f('ix_sys_config_create_dept'), 'sys_config', ['create_dept'], unique=False)
    op.create_index('uq_sysconfig_key', 'sys_config', ['config_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sysconfig_key', table_name='sys_config')
    op.drop_index(op.f('ix_sys_config_create_dept'), table_name='sys_config')
    op.drop_table('sys_config')
    # ### end Alembic commands ###
