"""initial schema 16 tables

Revision ID: a2f2dd7fba8f
Revises:
Create Date: 2026-06-16 21:43:30.813974

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a2f2dd7fba8f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_key",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("create_dept", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_key_create_dept"), "api_key", ["create_dept"], unique=False)
    op.create_index(op.f("ix_api_key_key_hash"), "api_key", ["key_hash"], unique=False)
    op.create_index(op.f("ix_api_key_status"), "api_key", ["status"], unique=False)
    op.create_index(op.f("ix_api_key_user_id"), "api_key", ["user_id"], unique=False)
    op.create_index("uq_apikey_hash", "api_key", ["key_hash"], unique=True)
    op.create_table(
        "channel_key",
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("alias", sa.String(length=64), nullable=False),
        sa.Column("api_key_encrypted", sa.Text(), nullable=False),
        sa.Column("key_hint", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("rpm_limit", sa.Integer(), nullable=True),
        sa.Column("tpm_limit", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("create_dept", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_channel_key_create_dept"), "channel_key", ["create_dept"], unique=False)
    op.create_index(op.f("ix_channel_key_channel_id"), "channel_key", ["channel_id"], unique=False)
    op.create_index(
        "ix_channel_key_channel_status", "channel_key", ["channel_id", "status"], unique=False
    )
    op.create_index(op.f("ix_channel_key_status"), "channel_key", ["status"], unique=False)
    op.create_table(
        "logical_model",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("context_length", sa.Integer(), nullable=True),
        sa.Column("price_input", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("price_output", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("create_dept", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_logical_model_create_dept"), "logical_model", ["create_dept"], unique=False)
    op.create_index(op.f("ix_logical_model_category"), "logical_model", ["category"], unique=False)
    op.create_index(op.f("ix_logical_model_status"), "logical_model", ["status"], unique=False)
    op.create_index(
        "uq_logical_model_name_active",
        "logical_model",
        ["name"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "model_deployment",
        sa.Column("logical_model_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("upstream_model", sa.String(length=128), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("create_dept", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_deployment_create_dept"), "model_deployment", ["create_dept"], unique=False)
    op.create_index(
        "ix_deployment_logical_status",
        "model_deployment",
        ["logical_model_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_deployment_channel_id"), "model_deployment", ["channel_id"], unique=False
    )
    op.create_index(
        op.f("ix_model_deployment_logical_model_id"),
        "model_deployment",
        ["logical_model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_deployment_status"), "model_deployment", ["status"], unique=False
    )
    op.create_index(
        "uq_deployment_logical_model_channel_active",
        "model_deployment",
        ["logical_model_id", "channel_id"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "quota",
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("scope_id", sa.BigInteger(), nullable=True),
        sa.Column("logical_model_id", sa.BigInteger(), nullable=True),
        sa.Column("period", sa.String(length=16), nullable=False),
        sa.Column("metric", sa.String(length=16), nullable=False),
        sa.Column("limit_value", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("enforce", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("create_dept", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'global' AND scope_id IS NULL) OR (scope <> 'global' AND scope_id IS NOT NULL)",
            name="ck_quota_scope_id_presence",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quota_create_dept"), "quota", ["create_dept"], unique=False)
    op.create_index(op.f("ix_quota_logical_model_id"), "quota", ["logical_model_id"], unique=False)
    op.create_index(op.f("ix_quota_scope"), "quota", ["scope"], unique=False)
    op.create_index(op.f("ix_quota_scope_id"), "quota", ["scope_id"], unique=False)
    op.create_index(op.f("ix_quota_status"), "quota", ["status"], unique=False)
    op.create_index(
        "uq_quota_scope_model_period_metric_active",
        "quota",
        ["scope", "scope_id", "logical_model_id", "period", "metric"],
        unique=True,
        postgresql_nulls_not_distinct=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "sys_department",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("create_dept", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sys_department_create_dept"), "sys_department", ["create_dept"], unique=False)
    op.create_index(
        op.f("ix_sys_department_external_id"), "sys_department", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_sys_department_parent_id"), "sys_department", ["parent_id"], unique=False
    )
    op.create_index(
        "uq_dept_external_active",
        "sys_department",
        ["external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL AND is_deleted = false"),
    )
    op.create_table(
        "sys_menu",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("menu_type", sa.String(length=8), nullable=False),
        sa.Column("perms", sa.String(length=128), nullable=True),
        sa.Column("path", sa.String(length=255), nullable=True),
        sa.Column("component", sa.String(length=255), nullable=True),
        sa.Column("query_param", sa.String(length=255), nullable=True),
        sa.Column("is_frame", sa.Boolean(), nullable=False),
        sa.Column("is_cache", sa.Boolean(), nullable=False),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("create_dept", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sys_menu_create_dept"), "sys_menu", ["create_dept"], unique=False)
    op.create_index(op.f("ix_sys_menu_parent_id"), "sys_menu", ["parent_id"], unique=False)
    op.create_index(op.f("ix_sys_menu_perms"), "sys_menu", ["perms"], unique=False)
    op.create_table(
        "sys_role",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("data_scope", sa.String(length=16), nullable=False),
        sa.Column("menu_check_strictly", sa.Boolean(), nullable=False),
        sa.Column("dept_check_strictly", sa.Boolean(), nullable=False),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("create_dept", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sys_role_create_dept"), "sys_role", ["create_dept"], unique=False)
    op.create_index(op.f("ix_sys_role_code"), "sys_role", ["code"], unique=False)
    op.create_index(
        "uq_role_code_active",
        "sys_role",
        ["code"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "sys_role_dept",
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("dept_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "dept_id", name="uq_role_dept"),
    )
    op.create_index(op.f("ix_sys_role_dept_dept_id"), "sys_role_dept", ["dept_id"], unique=False)
    op.create_index(op.f("ix_sys_role_dept_role_id"), "sys_role_dept", ["role_id"], unique=False)
    op.create_table(
        "sys_role_menu",
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("menu_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "menu_id", name="uq_role_menu"),
    )
    op.create_index(op.f("ix_sys_role_menu_menu_id"), "sys_role_menu", ["menu_id"], unique=False)
    op.create_index(op.f("ix_sys_role_menu_role_id"), "sys_role_menu", ["role_id"], unique=False)
    op.create_table(
        "sys_user",
        sa.Column("employee_no", sa.String(length=64), nullable=False),
        sa.Column("legacy_employee_no", sa.String(length=64), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("real_name", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("mobile", sa.String(length=32), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("department_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("preferred_locale", sa.String(length=16), server_default="zh-CN", nullable=False),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("create_dept", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sys_user_create_dept"), "sys_user", ["create_dept"], unique=False)
    op.create_index(op.f("ix_sys_user_department_id"), "sys_user", ["department_id"], unique=False)
    op.create_index(op.f("ix_sys_user_email"), "sys_user", ["email"], unique=False)
    op.create_index(op.f("ix_sys_user_employee_no"), "sys_user", ["employee_no"], unique=False)
    op.create_index(
        op.f("ix_sys_user_legacy_employee_no"), "sys_user", ["legacy_employee_no"], unique=False
    )
    op.create_index(op.f("ix_sys_user_mobile"), "sys_user", ["mobile"], unique=False)
    op.create_index(op.f("ix_sys_user_status"), "sys_user", ["status"], unique=False)
    op.create_index(
        "uq_user_employee_no_active",
        "sys_user",
        ["employee_no"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_index(
        "uq_user_legacy_no_active",
        "sys_user",
        ["legacy_employee_no"],
        unique=True,
        postgresql_where=sa.text("legacy_employee_no IS NOT NULL AND is_deleted = false"),
    )
    op.create_index(
        "uq_user_username_active",
        "sys_user",
        ["username"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "sys_user_oauth",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("uuid", sa.String(length=64), nullable=False),
        sa.Column("nickname", sa.String(length=64), nullable=True),
        sa.Column("avatar", sa.String(length=1000), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("gender", sa.String(length=16), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("create_dept", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sys_user_oauth_create_dept"), "sys_user_oauth", ["create_dept"], unique=False)
    op.create_index(op.f("ix_sys_user_oauth_source"), "sys_user_oauth", ["source"], unique=False)
    op.create_index(op.f("ix_sys_user_oauth_user_id"), "sys_user_oauth", ["user_id"], unique=False)
    op.create_index(op.f("ix_sys_user_oauth_uuid"), "sys_user_oauth", ["uuid"], unique=False)
    op.create_index(
        "uq_oauth_source_uuid_active",
        "sys_user_oauth",
        ["source", "uuid"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_index(
        "uq_oauth_user_source_active",
        "sys_user_oauth",
        ["user_id", "source"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "sys_user_role",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_role"),
    )
    op.create_index(op.f("ix_sys_user_role_role_id"), "sys_user_role", ["role_id"], unique=False)
    op.create_index(op.f("ix_sys_user_role_user_id"), "sys_user_role", ["user_id"], unique=False)
    op.create_table(
        "upstream_channel",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("protocol", sa.String(length=16), nullable=False),
        sa.Column("api_base", sa.String(length=255), nullable=True),
        sa.Column("extra_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("create_dept", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_upstream_channel_create_dept"), "upstream_channel", ["create_dept"], unique=False)
    op.create_index(
        op.f("ix_upstream_channel_protocol"), "upstream_channel", ["protocol"], unique=False
    )
    op.create_index(
        op.f("ix_upstream_channel_provider"), "upstream_channel", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_upstream_channel_status"), "upstream_channel", ["status"], unique=False
    )
    op.create_index(
        "uq_channel_name_active",
        "upstream_channel",
        ["name"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "usage_record",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("api_key_id", sa.BigInteger(), nullable=True),
        sa.Column("logical_model_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=True),
        sa.Column("upstream_model", sa.String(length=128), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("downgraded_features", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_usage_logical_model_created",
        "usage_record",
        ["logical_model_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_usage_record_api_key_id"), "usage_record", ["api_key_id"], unique=False
    )
    op.create_index(
        op.f("ix_usage_record_channel_id"), "usage_record", ["channel_id"], unique=False
    )
    op.create_index(
        op.f("ix_usage_record_logical_model_id"), "usage_record", ["logical_model_id"], unique=False
    )
    op.create_index(
        op.f("ix_usage_record_request_id"), "usage_record", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_usage_record_status"), "usage_record", ["status"], unique=False)
    op.create_index(op.f("ix_usage_record_user_id"), "usage_record", ["user_id"], unique=False)
    op.create_index(
        "ix_usage_user_created", "usage_record", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "user_model_grant",
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("scope_id", sa.BigInteger(), nullable=False),
        sa.Column("logical_model_id", sa.BigInteger(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("create_dept", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_model_grant_create_dept"), "user_model_grant", ["create_dept"], unique=False)
    op.create_index(
        op.f("ix_user_model_grant_logical_model_id"),
        "user_model_grant",
        ["logical_model_id"],
        unique=False,
    )
    op.create_index(op.f("ix_user_model_grant_scope"), "user_model_grant", ["scope"], unique=False)
    op.create_index(
        op.f("ix_user_model_grant_scope_id"), "user_model_grant", ["scope_id"], unique=False
    )
    op.create_index(
        "uq_grant_one_default",
        "user_model_grant",
        ["scope", "scope_id"],
        unique=True,
        postgresql_where=sa.text("is_default = true AND is_deleted = false"),
    )
    op.create_index(
        "uq_grant_scope_logical_model_active",
        "user_model_grant",
        ["scope", "scope_id", "logical_model_id"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_grant_scope_logical_model_active",
        table_name="user_model_grant",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(
        "uq_grant_one_default",
        table_name="user_model_grant",
        postgresql_where=sa.text("is_default = true AND is_deleted = false"),
    )
    op.drop_index(op.f("ix_user_model_grant_scope_id"), table_name="user_model_grant")
    op.drop_index(op.f("ix_user_model_grant_scope"), table_name="user_model_grant")
    op.drop_index(op.f("ix_user_model_grant_logical_model_id"), table_name="user_model_grant")
    op.drop_index(op.f("ix_user_model_grant_create_dept"), table_name="user_model_grant")
    op.drop_table("user_model_grant")
    op.drop_index("ix_usage_user_created", table_name="usage_record")
    op.drop_index(op.f("ix_usage_record_user_id"), table_name="usage_record")
    op.drop_index(op.f("ix_usage_record_status"), table_name="usage_record")
    op.drop_index(op.f("ix_usage_record_request_id"), table_name="usage_record")
    op.drop_index(op.f("ix_usage_record_logical_model_id"), table_name="usage_record")
    op.drop_index(op.f("ix_usage_record_channel_id"), table_name="usage_record")
    op.drop_index(op.f("ix_usage_record_api_key_id"), table_name="usage_record")
    op.drop_index("ix_usage_logical_model_created", table_name="usage_record")
    op.drop_table("usage_record")
    op.drop_index(
        "uq_channel_name_active",
        table_name="upstream_channel",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_upstream_channel_status"), table_name="upstream_channel")
    op.drop_index(op.f("ix_upstream_channel_provider"), table_name="upstream_channel")
    op.drop_index(op.f("ix_upstream_channel_protocol"), table_name="upstream_channel")
    op.drop_index(op.f("ix_upstream_channel_create_dept"), table_name="upstream_channel")
    op.drop_table("upstream_channel")
    op.drop_index(op.f("ix_sys_user_role_user_id"), table_name="sys_user_role")
    op.drop_index(op.f("ix_sys_user_role_role_id"), table_name="sys_user_role")
    op.drop_table("sys_user_role")
    op.drop_index(
        "uq_oauth_user_source_active",
        table_name="sys_user_oauth",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(
        "uq_oauth_source_uuid_active",
        table_name="sys_user_oauth",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_sys_user_oauth_uuid"), table_name="sys_user_oauth")
    op.drop_index(op.f("ix_sys_user_oauth_user_id"), table_name="sys_user_oauth")
    op.drop_index(op.f("ix_sys_user_oauth_source"), table_name="sys_user_oauth")
    op.drop_index(op.f("ix_sys_user_oauth_create_dept"), table_name="sys_user_oauth")
    op.drop_table("sys_user_oauth")
    op.drop_index(
        "uq_user_username_active",
        table_name="sys_user",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(
        "uq_user_legacy_no_active",
        table_name="sys_user",
        postgresql_where=sa.text("legacy_employee_no IS NOT NULL AND is_deleted = false"),
    )
    op.drop_index(
        "uq_user_employee_no_active",
        table_name="sys_user",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_sys_user_status"), table_name="sys_user")
    op.drop_index(op.f("ix_sys_user_mobile"), table_name="sys_user")
    op.drop_index(op.f("ix_sys_user_legacy_employee_no"), table_name="sys_user")
    op.drop_index(op.f("ix_sys_user_employee_no"), table_name="sys_user")
    op.drop_index(op.f("ix_sys_user_email"), table_name="sys_user")
    op.drop_index(op.f("ix_sys_user_department_id"), table_name="sys_user")
    op.drop_index(op.f("ix_sys_user_create_dept"), table_name="sys_user")
    op.drop_table("sys_user")
    op.drop_index(op.f("ix_sys_role_menu_role_id"), table_name="sys_role_menu")
    op.drop_index(op.f("ix_sys_role_menu_menu_id"), table_name="sys_role_menu")
    op.drop_table("sys_role_menu")
    op.drop_index(op.f("ix_sys_role_dept_role_id"), table_name="sys_role_dept")
    op.drop_index(op.f("ix_sys_role_dept_dept_id"), table_name="sys_role_dept")
    op.drop_table("sys_role_dept")
    op.drop_index(
        "uq_role_code_active", table_name="sys_role", postgresql_where=sa.text("is_deleted = false")
    )
    op.drop_index(op.f("ix_sys_role_code"), table_name="sys_role")
    op.drop_index(op.f("ix_sys_role_create_dept"), table_name="sys_role")
    op.drop_table("sys_role")
    op.drop_index(op.f("ix_sys_menu_perms"), table_name="sys_menu")
    op.drop_index(op.f("ix_sys_menu_parent_id"), table_name="sys_menu")
    op.drop_index(op.f("ix_sys_menu_create_dept"), table_name="sys_menu")
    op.drop_table("sys_menu")
    op.drop_index(
        "uq_dept_external_active",
        table_name="sys_department",
        postgresql_where=sa.text("external_id IS NOT NULL AND is_deleted = false"),
    )
    op.drop_index(op.f("ix_sys_department_parent_id"), table_name="sys_department")
    op.drop_index(op.f("ix_sys_department_external_id"), table_name="sys_department")
    op.drop_index(op.f("ix_sys_department_create_dept"), table_name="sys_department")
    op.drop_table("sys_department")
    op.drop_index(
        "uq_quota_scope_model_period_metric_active",
        table_name="quota",
        postgresql_nulls_not_distinct=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_quota_status"), table_name="quota")
    op.drop_index(op.f("ix_quota_scope_id"), table_name="quota")
    op.drop_index(op.f("ix_quota_scope"), table_name="quota")
    op.drop_index(op.f("ix_quota_logical_model_id"), table_name="quota")
    op.drop_index(op.f("ix_quota_create_dept"), table_name="quota")
    op.drop_table("quota")
    op.drop_index(
        "uq_deployment_logical_model_channel_active",
        table_name="model_deployment",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_model_deployment_status"), table_name="model_deployment")
    op.drop_index(op.f("ix_model_deployment_logical_model_id"), table_name="model_deployment")
    op.drop_index(op.f("ix_model_deployment_channel_id"), table_name="model_deployment")
    op.drop_index("ix_deployment_logical_status", table_name="model_deployment")
    op.drop_index(op.f("ix_model_deployment_create_dept"), table_name="model_deployment")
    op.drop_table("model_deployment")
    op.drop_index(
        "uq_logical_model_name_active",
        table_name="logical_model",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(op.f("ix_logical_model_status"), table_name="logical_model")
    op.drop_index(op.f("ix_logical_model_category"), table_name="logical_model")
    op.drop_index(op.f("ix_logical_model_create_dept"), table_name="logical_model")
    op.drop_table("logical_model")
    op.drop_index(op.f("ix_channel_key_status"), table_name="channel_key")
    op.drop_index("ix_channel_key_channel_status", table_name="channel_key")
    op.drop_index(op.f("ix_channel_key_channel_id"), table_name="channel_key")
    op.drop_index(op.f("ix_channel_key_create_dept"), table_name="channel_key")
    op.drop_table("channel_key")
    op.drop_index("uq_apikey_hash", table_name="api_key")
    op.drop_index(op.f("ix_api_key_user_id"), table_name="api_key")
    op.drop_index(op.f("ix_api_key_status"), table_name="api_key")
    op.drop_index(op.f("ix_api_key_key_hash"), table_name="api_key")
    op.drop_index(op.f("ix_api_key_create_dept"), table_name="api_key")
    op.drop_table("api_key")
    # ### end Alembic commands ###
