"""add oper_log and login_log audit tables

Revision ID: dd58396c39de
Revises: 2052dfbbf16e
Create Date: 2026-06-17 23:23:56.685826

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd58396c39de'
down_revision: str | None = '2052dfbbf16e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_log',
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='命中的 users.id；用户名无法解析时为空'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='尝试登录的用户名（无论成败都记录）'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='登录结果 AuditOutcome：success | failure'),
    sa.Column('failure_reason', sa.String(length=64), nullable=True, comment='失败原因 LoginFailureReason；成功为空'),
    sa.Column('request_ip', sa.String(length=45), nullable=True, comment='登录来源 IP（兼容 IPv6）'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='登录 User-Agent'),
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='关联 trace_id'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.PrimaryKeyConstraint('id'),
    comment='登录审计日志：记录每次登录尝试（成功/失败、用户名、IP、UA、失败原因），追加写不可改'
    )
    op.create_index(op.f('ix_login_log_status'), 'login_log', ['status'], unique=False)
    op.create_index(op.f('ix_login_log_trace_id'), 'login_log', ['trace_id'], unique=False)
    op.create_index('ix_login_log_user_created', 'login_log', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_login_log_user_id'), 'login_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_login_log_username'), 'login_log', ['username'], unique=False)
    op.create_index('ix_login_log_username_created', 'login_log', ['username', 'created_at'], unique=False)
    op.create_table('oper_log',
    sa.Column('actor_id', sa.BigInteger(), nullable=True, comment='操作人 users.id（逻辑引用）；null=系统操作'),
    sa.Column('actor_name', sa.String(length=64), nullable=True, comment='操作人用户名快照（冗余，审计需在用户改名/删除后仍可读）'),
    sa.Column('module', sa.String(length=64), nullable=False, comment='业务模块/资源域（如 user/role/menu/dept）'),
    sa.Column('action', sa.String(length=32), nullable=False, comment='操作动作（如 create/update/delete/batch_delete）'),
    sa.Column('method', sa.String(length=8), nullable=False, comment='HTTP 方法'),
    sa.Column('path', sa.String(length=255), nullable=False, comment='请求路径'),
    sa.Column('target_id', sa.String(length=64), nullable=True, comment='受影响资源 id（雪花，字符串存储）'),
    sa.Column('request_ip', sa.String(length=45), nullable=True, comment='请求来源 IP（兼容 IPv6）'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='请求 User-Agent'),
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='关联 trace_id（贯穿结构化日志）'),
    sa.Column('before_value', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True, comment='变更前快照；null=不适用（如创建/查询）'),
    sa.Column('after_value', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True, comment='变更后快照；null=不适用（如删除/查询）'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='操作结果 AuditOutcome：success | failure'),
    sa.Column('error_code', sa.String(length=64), nullable=True, comment='失败时的 ErrorCode 值；成功为空'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='端到端处理耗时（毫秒）'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.PrimaryKeyConstraint('id'),
    comment='操作审计日志：后台写操作留痕（谁/何时/对什么/做了什么/前后值/trace_id/IP），追加写不可改'
    )
    op.create_index('ix_oper_log_actor_created', 'oper_log', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_oper_log_actor_id'), 'oper_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_oper_log_module'), 'oper_log', ['module'], unique=False)
    op.create_index('ix_oper_log_module_created', 'oper_log', ['module', 'created_at'], unique=False)
    op.create_index(op.f('ix_oper_log_status'), 'oper_log', ['status'], unique=False)
    op.create_index(op.f('ix_oper_log_trace_id'), 'oper_log', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oper_log_trace_id'), table_name='oper_log')
    op.drop_index(op.f('ix_oper_log_status'), table_name='oper_log')
    op.drop_index('ix_oper_log_module_created', table_name='oper_log')
    op.drop_index(op.f('ix_oper_log_module'), table_name='oper_log')
    op.drop_index(op.f('ix_oper_log_actor_id'), table_name='oper_log')
    op.drop_index('ix_oper_log_actor_created', table_name='oper_log')
    op.drop_table('oper_log')
    op.drop_index('ix_login_log_username_created', table_name='login_log')
    op.drop_index(op.f('ix_login_log_username'), table_name='login_log')
    op.drop_index(op.f('ix_login_log_user_id'), table_name='login_log')
    op.drop_index('ix_login_log_user_created', table_name='login_log')
    op.drop_index(op.f('ix_login_log_trace_id'), table_name='login_log')
    op.drop_index(op.f('ix_login_log_status'), table_name='login_log')
    op.drop_table('login_log')
    # ### end Alembic commands ###
