"""add attach table and users.avatar column

Revision ID: e2bec51025e0
Revises: 86f8cd47f40f
Create Date: 2026-06-18 10:02:02.045233

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bec51025e0'
down_revision: str | None = '86f8cd47f40f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attach',
    sa.Column('object_key', sa.String(length=512), nullable=False, comment='桶内相对路径（全局唯一），如 avatar/2026/06/{id}.webp'),
    sa.Column('bucket', sa.String(length=128), nullable=False, comment='所在桶名（冗余存，便于将来多桶/迁移/审计）'),
    sa.Column('original_name', sa.String(length=255), nullable=True, comment='上传时原始文件名（下载用，可空）'),
    sa.Column('content_type', sa.String(length=128), nullable=False, comment='MIME 类型，如 image/webp'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件字节数（存入对象存储后的最终大小）'),
    sa.Column('biz_type', sa.String(length=32), nullable=False, comment='用途 AttachBizType：avatar | attachment'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 users.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 department.id（逻辑引用），用于数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 users.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.PrimaryKeyConstraint('id'),
    comment='附件：对象存储文件元数据；私有桶读取走短期预签名 URL，DB 只存 object key'
    )
    op.create_index(op.f('ix_attach_biz_type'), 'attach', ['biz_type'], unique=False)
    op.create_index(op.f('ix_attach_create_dept'), 'attach', ['create_dept'], unique=False)
    op.create_index('uq_attach_object_key', 'attach', ['object_key'], unique=True)
    op.add_column('users', sa.Column('avatar', sa.BigInteger(), nullable=True, comment='头像附件 attach.id（逻辑引用，无物理外键）；读取时现算预签名 URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_index('uq_attach_object_key', table_name='attach')
    op.drop_index(op.f('ix_attach_create_dept'), table_name='attach')
    op.drop_index(op.f('ix_attach_biz_type'), table_name='attach')
    op.drop_table('attach')
    # ### end Alembic commands ###
