"""add_gateway_request_log_rate_limit_rule_catalog_ops

Revision ID: ec3ad92ab152
Revises: e2bec51025e0
Create Date: 2026-06-23 19:25:40.978257

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec3ad92ab152'
down_revision: str | None = 'e2bec51025e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_change_log',
    sa.Column('actor_id', sa.BigInteger(), nullable=True, comment='操作人 users.id'),
    sa.Column('resource_type', sa.String(length=32), nullable=False, comment='变更资源类型：channel | key | model | deployment'),
    sa.Column('resource_id', sa.String(length=64), nullable=True, comment='变更资源 ID'),
    sa.Column('action', sa.String(length=32), nullable=False, comment='操作：create | update | delete | rotate | auto_disable'),
    sa.Column('before_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='变更前值（脱敏）'),
    sa.Column('after_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='变更后值（脱敏）'),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='差异摘要（field→{old,new}）'),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True, comment='关联配置快照 ID（变更前自动创建）'),
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='请求 trace_id（关联网关日志）'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.PrimaryKeyConstraint('id'),
    comment='目录配置变更日志：每次渠道/模型/部署/密钥变更的前后快照'
    )
    op.create_index(op.f('ix_catalog_change_log_action'), 'catalog_change_log', ['action'], unique=False)
    op.create_index(op.f('ix_catalog_change_log_actor_id'), 'catalog_change_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_catalog_change_log_resource_type'), 'catalog_change_log', ['resource_type'], unique=False)
    op.create_table('catalog_config_snapshot',
    sa.Column('actor_id', sa.BigInteger(), nullable=True, comment='创建快照的操作人'),
    sa.Column('reason', sa.String(length=32), nullable=False, comment='创建原因：known_good | pre_write | rollback | dry_run'),
    sa.Column('config_hash', sa.String(length=64), nullable=False, comment='配置内容 SHA-256（用于去重和比对）'),
    sa.Column('is_known_good', sa.Boolean(), nullable=False, comment='是否为最近一次验证通过的已知良好配置'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='完整配置 JSON：channels/keys/models/deployments（密钥字段保留加密形式）'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（回滚时记录原因）'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.PrimaryKeyConstraint('id'),
    comment='目录配置快照：用于 dry-run 校验和回滚'
    )
    op.create_index(op.f('ix_catalog_config_snapshot_config_hash'), 'catalog_config_snapshot', ['config_hash'], unique=False)
    op.create_table('gateway_request_log',
    sa.Column('request_id', sa.String(length=64), nullable=False, comment='请求唯一标识（关联 usage_record.request_id）'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='调用者 users.id'),
    sa.Column('api_key_id', sa.BigInteger(), nullable=True, comment='调用者 api_key.id'),
    sa.Column('logical_model_id', sa.BigInteger(), nullable=True, comment='逻辑模型 logical_model.id'),
    sa.Column('model', sa.String(length=64), nullable=True, comment='请求中的 model 名（逻辑模型 name）'),
    sa.Column('channel_id', sa.BigInteger(), nullable=True, comment='实际路由到的渠道 upstream_channel.id'),
    sa.Column('upstream_model', sa.String(length=128), nullable=True, comment='上游真实模型名'),
    sa.Column('provider', sa.String(length=32), nullable=True, comment='上游厂商（openai/anthropic/gemini）'),
    sa.Column('status_code', sa.Integer(), nullable=False, comment='HTTP 状态码（200/429/502/504 等）'),
    sa.Column('error_code', sa.String(length=64), nullable=True, comment='ErrorCode 枚举值（仅失败时有值）'),
    sa.Column('error_body', sa.Text(), nullable=True, comment='上游错误体（截断至 2048 字符，脱敏）'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='端到端延迟（毫秒）'),
    sa.Column('ttft_ms', sa.Integer(), nullable=True, comment='首 token 延迟（毫秒，仅流式）'),
    sa.Column('tokens_in', sa.Integer(), nullable=False, comment='输入 token 数'),
    sa.Column('tokens_out', sa.Integer(), nullable=False, comment='输出 token 数'),
    sa.Column('stream', sa.Boolean(), nullable=False, comment='是否流式请求'),
    sa.Column('cache_hit', sa.Boolean(), nullable=False, comment='是否命中响应缓存'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='litellm Router 重试次数'),
    sa.Column('fallback_used', sa.Boolean(), nullable=False, comment='是否使用了 fallback 渠道'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id'),
    comment='网关请求日志：每次 LLM 调用的路由/错误/延迟明细（运维排障用）'
    )
    op.create_index(op.f('ix_gateway_request_log_provider'), 'gateway_request_log', ['provider'], unique=False)
    op.create_index(op.f('ix_gateway_request_log_user_id'), 'gateway_request_log', ['user_id'], unique=False)
    op.create_index('ix_gwlog_channel_created', 'gateway_request_log', ['channel_id', 'created_at'], unique=False)
    op.create_index('ix_gwlog_model_created', 'gateway_request_log', ['model', 'created_at'], unique=False)
    op.create_index('ix_gwlog_status_code', 'gateway_request_log', ['status_code'], unique=False)
    op.create_index('ix_gwlog_user_created', 'gateway_request_log', ['user_id', 'created_at'], unique=False)
    op.create_table('rate_limit_rule',
    sa.Column('subject_type', sa.String(length=16), nullable=False, comment='限制主体类型：global | user | department | api_key'),
    sa.Column('subject_id', sa.BigInteger(), nullable=True, comment='主体 ID（global 时为 null）'),
    sa.Column('logical_model_id', sa.BigInteger(), nullable=True, comment='限制特定模型（null=所有模型）'),
    sa.Column('rpm_limit', sa.Integer(), nullable=True, comment='每分钟请求上限（null=不限）'),
    sa.Column('tpm_limit', sa.Integer(), nullable=True, comment='每分钟 token 上限（null=不限）'),
    sa.Column('tpm_burst_limit', sa.Integer(), nullable=True, comment='TPM 突发上限（null=不限）'),
    sa.Column('max_concurrent', sa.Integer(), nullable=True, comment='最大并发流式请求数（null=不限）'),
    sa.Column('enforce', sa.Boolean(), nullable=False, comment='是否执行（false=仅记录不拦截）'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='active | disabled'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注说明'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='主键：雪花 ID，应用层分配（非自增）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删标记：true=已删除（逻辑删除，不物理删行）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人 users.id（逻辑引用，无物理外键）；null=系统操作'),
    sa.Column('create_dept', sa.BigInteger(), nullable=True, comment='创建部门 department.id（逻辑引用），用于数据权限过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（timestamptz，UTC，由数据库 now() 生成）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新人 users.id（逻辑引用）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（timestamptz，UTC，更新时自动刷新）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_type', 'subject_id', 'logical_model_id', name='uq_rate_limit_active_rule'),
    comment='速率限制规则：RPM/TPM/并发上限（流量整形，非计费配额）'
    )
    op.create_index(op.f('ix_rate_limit_rule_create_dept'), 'rate_limit_rule', ['create_dept'], unique=False)
    op.create_index(op.f('ix_rate_limit_rule_logical_model_id'), 'rate_limit_rule', ['logical_model_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_rule_status'), 'rate_limit_rule', ['status'], unique=False)
    op.create_index(op.f('ix_rate_limit_rule_subject_id'), 'rate_limit_rule', ['subject_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_rule_subject_type'), 'rate_limit_rule', ['subject_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_rule_subject_type'), table_name='rate_limit_rule')
    op.drop_index(op.f('ix_rate_limit_rule_subject_id'), table_name='rate_limit_rule')
    op.drop_index(op.f('ix_rate_limit_rule_status'), table_name='rate_limit_rule')
    op.drop_index(op.f('ix_rate_limit_rule_logical_model_id'), table_name='rate_limit_rule')
    op.drop_index(op.f('ix_rate_limit_rule_create_dept'), table_name='rate_limit_rule')
    op.drop_table('rate_limit_rule')
    op.drop_index('ix_gwlog_user_created', table_name='gateway_request_log')
    op.drop_index('ix_gwlog_status_code', table_name='gateway_request_log')
    op.drop_index('ix_gwlog_model_created', table_name='gateway_request_log')
    op.drop_index('ix_gwlog_channel_created', table_name='gateway_request_log')
    op.drop_index(op.f('ix_gateway_request_log_user_id'), table_name='gateway_request_log')
    op.drop_index(op.f('ix_gateway_request_log_provider'), table_name='gateway_request_log')
    op.drop_table('gateway_request_log')
    op.drop_index(op.f('ix_catalog_config_snapshot_config_hash'), table_name='catalog_config_snapshot')
    op.drop_table('catalog_config_snapshot')
    op.drop_index(op.f('ix_catalog_change_log_resource_type'), table_name='catalog_change_log')
    op.drop_index(op.f('ix_catalog_change_log_actor_id'), table_name='catalog_change_log')
    op.drop_index(op.f('ix_catalog_change_log_action'), table_name='catalog_change_log')
    op.drop_table('catalog_change_log')
    # ### end Alembic commands ###
